// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmjjslxoueqwykgryfjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttampzbHhvdWVxd3lrZ3J5ZmpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTc5MTgsImV4cCI6MjA2NjA5MzkxOH0.lyUL8o-330ZC_pGUb4TvPpY9uDHJ2lEIuoUynl67u_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);